### ISSUE TITLE
Form dirty with when mask loads with divisors

### ISSUE THREAD

**Issue by candreoliveira** [candreoliveira/ngMask#30]
http://plnkr.co/edit/Ahlzf0TXhcnNtlM45OQA?p=preview

**Comment by ldeavila** [comment]
+1

**Comment by ldeavila** [comment]
Tried updating the controller inside the post function but that does not update the parent form controller. Found this: http://stackoverflow.com/questions/19320062/accessing-parent-directives-controller-recursively-in-angularjs. It lets me update the parent form and set it to pristine but i'm not sure where to place such code so that the form is pristine only when the directive first renders the form. Thoughts?

**Comment by mvarshavsky** [comment]
Okay, my thinking was along similar lines to what @ldeavila is suggesting. Tag on some variable that would track if we're doing the initial $setViewValue call or not. If so, I was going to set pristine to true, then climb up to the form `$element.context.form` and set it to pristine as well. Obviously a hack, but whatever. Then I stumbled across this: https://github.com/zensh/ui-autocomplete/issues/6

So the pertinent snippet, inside parseViewValue, where we "Update view and model values":
```
  controller.$pristine = false
  controller.$setViewValue(angular.copy(viewValueWithDivisors), 'input');
  controller.$pristine = true
```
It appears to be working for me. Now I'm really bothered by not understanding *why* it is working. Why doesn't this code dirty up the form on initial load, but consecutive `keyup`'s, etc also have the desired behavior of making it dirty? I get that `ngModelController.$commitViewValue` only sets dirty when it is pristine... but what ever sets it dirty then?

@candreoliveira, what are your thoughts on this approach?

**Comment by belluccifranco** [comment]
+1
